### ISSUE TITLE
Code release as per GPLv3

### ISSUE THREAD

**Issue by Schischu** [iMaxxx/OpenSkin-Designer#1]
Hi there,

as happy as I am that my projects are continued, please be aware that e2skinner2 is licensed under the GNU GPLv3 license.
This fact is clearly stated on the project homepage (https://code.google.com/p/e2skinner2/).

So I hope you are planning on the release of the code in the foreseeable future.

BR
Schischu

**Comment by psych0d0g** [comment]
hai, so where is the source?

**Comment by sbeatz** [comment]
indeed - it's been 2 years now... without the source it is impossible to fix bugs...

**Comment by iMaxxx** [comment]
A bit late but done ;) 
sorry for the delay.

**Comment by Humaxx** [comment]
Is it allowed to use and  the source code and publish the new releases for bug fixes?

**Comment by iMaxxx** [comment]
Make a fork, make your changes an create a pull request if your version works better. Also new features are welcome.
